site_name: Enchantrix
theme:
  name: material
nav:
  - Home: index.md
  - Trix File Format: trix_format.md
  - Examples:
    - Trix & Sigil Chaining: trix_and_sigils.md
    - Hashing: hashing.md
    - Checksums: checksums.md
    - RSA: rsa.md
    - Standalone Sigils: standalone_sigils.md
